version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskr-web
    expose:
      - "5981"
    environment:
      FLASK_APP: flaskr
      FLASK_ENV: production
      DATABASE_URL: postgresql://flaskr:flaskr@db:5432/flaskr
    depends_on:
      - db
    volumes:
      - .:/app
      - instance-data:/app/instance

  nginx:
    image: nginx:alpine
    container_name: flaskr-nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/app:ro

  db:
    image: postgres:15
    container_name: flaskr-db
    restart: always
    environment:
      POSTGRES_USER: flaskr
      POSTGRES_PASSWORD: flaskr
      POSTGRES_DB: flaskr
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  instance-data: